/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrcamentosNovoRouteImport } from './routes/orcamentos.novo'
import { Route as OrcamentosIdRouteImport } from './routes/orcamentos.$id'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'

const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosNovoRoute = OrcamentosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => OrcamentosRoute,
} as any)
const OrcamentosIdRoute = OrcamentosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrcamentosRoute,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/orcamentos': typeof OrcamentosRouteWithChildren
  '/pipeline': typeof PipelineRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/orcamentos/$id': typeof OrcamentosIdRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/orcamentos': typeof OrcamentosRouteWithChildren
  '/pipeline': typeof PipelineRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/orcamentos/$id': typeof OrcamentosIdRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/orcamentos': typeof OrcamentosRouteWithChildren
  '/pipeline': typeof PipelineRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/orcamentos/$id': typeof OrcamentosIdRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/dashboard'
    | '/leads'
    | '/login'
    | '/orcamentos'
    | '/pipeline'
    | '/clientes/$id'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/dashboard'
    | '/leads'
    | '/login'
    | '/orcamentos'
    | '/pipeline'
    | '/clientes/$id'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/dashboard'
    | '/leads'
    | '/login'
    | '/orcamentos'
    | '/pipeline'
    | '/clientes/$id'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  OrcamentosRoute: typeof OrcamentosRouteWithChildren
  PipelineRoute: typeof PipelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos/novo': {
      id: '/orcamentos/novo'
      path: '/novo'
      fullPath: '/orcamentos/novo'
      preLoaderRoute: typeof OrcamentosNovoRouteImport
      parentRoute: typeof OrcamentosRoute
    }
    '/orcamentos/$id': {
      id: '/orcamentos/$id'
      path: '/$id'
      fullPath: '/orcamentos/$id'
      preLoaderRoute: typeof OrcamentosIdRouteImport
      parentRoute: typeof OrcamentosRoute
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof ClientesRoute
    }
  }
}

interface ClientesRouteChildren {
  ClientesIdRoute: typeof ClientesIdRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesIdRoute: ClientesIdRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

interface OrcamentosRouteChildren {
  OrcamentosIdRoute: typeof OrcamentosIdRoute
  OrcamentosNovoRoute: typeof OrcamentosNovoRoute
}

const OrcamentosRouteChildren: OrcamentosRouteChildren = {
  OrcamentosIdRoute: OrcamentosIdRoute,
  OrcamentosNovoRoute: OrcamentosNovoRoute,
}

const OrcamentosRouteWithChildren = OrcamentosRoute._addFileChildren(
  OrcamentosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  OrcamentosRoute: OrcamentosRouteWithChildren,
  PipelineRoute: PipelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
